default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ENV['PSQL_USERNAME']
  password: ENV['PSQL_PASSWORD']

development:
  <<: *default
  database: gotta_finish_em_all_development

test:
  <<: *default
  database: gotta_finish_em_all_test

production:
  <<: *default
  database: gotta_finish_em_all_production
  username: gotta_finish_em_all
  password: <%= ENV['GOTTA_FINISH_EM_ALL_DATABASE_PASSWORD'] %>
